
##################################################################
###                                                            ###
###   ######  #          #  #######  #######   #######         ###
###   #       # #      # #  #     #  #      #     #            ###
###   ######  #  #    #  #  #######  #######      #            ###
###        #  #   #  #   #  #     #  #     #      #            ###
###   ######  #    #     #  #     #  #      #     #            ###
###                                                            ###
###   #######  #        #     #  #######  #  #     #  #######  ###
###   #     #  #        #     #  #        #  # #   #  #        ###
###   #######  #        #     #  #    ##  #  #  #  #  #######  ###
###   #        #        #     #  #     #  #  #   # #        #  ###
###   #        #######  #######  #######  #  #     #  #######  ###
###                                                            ###
##################################################################

##################################################################
#                                                                #
#        %player% = Player that joined or left the server        #
#                                                                #
##################################################################

Join-Message: "%player% has joined the server"
New-Join-Message: "%player% has joined for the first time"
Leave-Message: "%player% just left the server"